//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KitapTablo()
        {
            this.satın_alan = new HashSet<satın_alan>();
            this.satiş_yapan = new HashSet<satiş_yapan>();
        }
    
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public string YazarAdiSoyadi { get; set; }
        public short KitapSayfaSayisi { get; set; }
        public Nullable<System.DateTime> KitapBasimTarihi { get; set; }
        public string YayinEvi { get; set; }
        public double KitapFiyat { get; set; }
        public Nullable<short> KitapStok { get; set; }
        public string UrunTip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satın_alan> satın_alan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satiş_yapan> satiş_yapan { get; set; }
    }
}
