//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class satın_alan
    {
        public int SatinAlanID { get; set; }
        public int KullaniciID { get; set; }
        public int KitapID { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual KitapTablo KitapTablo { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
